version: '{build}'
skip_tags: true

environment:
  MAVEN_VERSION: 3.5.0
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk11

os: Windows Server 2012

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        Write-Host "Downloading Maven $env:MAVEN_VERSION"
        (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g

build_script:
  - ./mvnw clean verify -P run-its -B -V

cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2 -> pom.xml
